name = "kvrocks-repo-gateway"
main = "worker.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[vars]
GITHUB_REPO = "rawvoid/kvrocks-fpm"
METADATA_ORIGIN = "https://rawvoid.github.io/kvrocks-fpm"

routes = [
  { pattern = "kvrocks.kryo.eu.org/*", custom_domain = true }
]
